cache:
  directories:
    - /usr/share/lua
    - /usr/bin/luarocks


before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential curl wget unzip git openssl lua5.2 lua5.2-dev libev-dev libjs-jquery -y
  - wget -O /tmp/luarocks.zip https://github.com/keplerproject/luarocks/archive/v3.0.1.zip
  - unzip /tmp/luarocks.zip -d /tmp
  - (cd /tmp/luarocks-3.0.1 && ./configure --prefix=/usr --lua-version=5.2)
  - make -C /tmp/luarocks-3.0.1 build
  - sudo make -C /tmp/luarocks-3.0.1 install
  - sudo luarocks install serpent
  - sudo luarocks install busted
  - sudo luarocks install luacheck
  - sudo luarocks install faketorio

script:
  - luacheck ./src/*.lua --globals todo mod_gui script game defines data serpent settings global
  - luacheck ./src/todo/*.lua --globals todo mod_gui script game defines data serpent settings global
  - faketorio package -c .travis/.faketorio -v
  # - busted -- removed until faketorio tests are working correctly. even then wont be used much, though...

deploy:
  provider: releases
  api_key: "${TOKEN}"
  file: "target/Todo-List_${TRAVIS_TAG}.zip"
  skip_cleanup: true
  on:
    tags: true